name: InBerlinWohnen Monitor

##on:
 ## schedule:
 ##   - cron: "*/5 * * * *" # runs every 2 minutes
  ##workflow_dispatch: # allows manual run

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run housing monitor
        run: bash check.sh
       ## env:
        ##  TG_TOKEN: ${{ secrets.TG_TOKEN }}
        ##  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
